Add guardrails orchestrator controller
trustyai-explainability/trustyai-service-operator pull request #348
Opened 2024-10-29 15:22 UTC by christinaexyou

2025-01-08 23:13 UTC, evaline-ju commented on cmd/main.go
> -		Namespace:              "", // We are defining a cluster-scoped operator
General q for my understanding - would this affect other features? Otherwise why was it cluster-scoped to begin with?

2025-01-09 11:40 UTC, ruivieira requested changes

2025-01-09 11:40 UTC, ruivieira commented on config/base/params.env
> +guardrails-orchestrator-image=quay.io/rh-ee-mmisiura/fms-orchestr8-nlp:0.7.0
This needs to point to the TrustyAI quay.io image

2025-01-09 11:40 UTC, ruivieira commented on config/overlays/odh/params.env
> +guardrails-orchestrator-image=quay.io/rh-ee-mmisiura/fms-orchestr8-nlp:0.7.0
Likewise, this needs to point to TrustyAI quay's image

2025-01-09 11:40 UTC, ruivieira commented on config/overlays/rhoai/params.env
> +guardrails-orchestrator-image=quay.io/rh-ee-mmisiura/fms-orchestr8-nlp:0.7.0
Point to TrustyAI quay's image

2025-01-09 11:40 UTC, ruivieira commented on controllers/gorch/constants.go
> +	orchestratorImage = string("quay.io/rh-ee-mmisiura/fms-orchestr8-nlp:main_79434f")
Shouldn't this be fetched from the operator's config map?

2025-01-09 11:40 UTC, ruivieira commented on controllers/gorch/templates/deployment.tmpl.yaml
> +                app: {{.Name}}
I would suggest a few changes here:

* Use a constant name for component, no the deployment's name (for instance `guardrails-orchestrator`)
* I would also add these labels for consistency with other TrustyAI Kubernetes resources:

```
  labels:
    app: {{ .Name }}
    app.kubernetes.io/instance: {{ .Name }}
    app.kubernetes.io/name: {{ .Name }}
    app.kubernetes.io/part-of: trustyai
    app.kubernetes.io/version: {{ .Version }}
```

`Version` could be added to the constants.

2025-01-09 11:40 UTC, ruivieira commented on controllers/gorch/templates/deployment.tmpl.yaml
> +                    cpu: '1'
Should the limits and requests be configurable?

2025-01-09 11:40 UTC, ruivieira commented on controllers/gorch/templates/parser.go
> +package templates
This parser seems to be a duplicate of the TrustyAI service one. Is it possible to have a single, shared parser?

2025-01-09 11:40 UTC, ruivieira commented on controllers/gorch/templates/service.tmpl.yaml
> +    app: {{.Name}}
(Just a reminder that if the labels where changed for a previous comment, these should stay consistent)

2025-01-09 11:40 UTC, ruivieira commented on controllers/utils/utils.go
>  import (
Is this is the shared parser, then both the orchestrator's and service's parsers could be removed (and this one used, instead)

2025-01-09 11:40 UTC, ruivieira commented on controllers/gorch/guardrailsorchestrator_controller.go
> +		return ctrl.Result{Requeue: true}, nil
I think the reconciler should not requeue here, but continute the reconciliation

2025-01-09 11:40 UTC, ruivieira commented on controllers/gorch/guardrailsorchestrator_controller.go
> +		return ctrl.Result{Requeue: true}, nil
Likewise, continue if no error.

2025-01-09 11:40 UTC, ruivieira commented on controllers/gorch/guardrailsorchestrator_controller.go
> +		return ctrl.Result{Requeue: true}, nil
Same as the previous

2025-01-09 11:40 UTC, ruivieira commented on controllers/gorch/guardrailsorchestrator_controller.go
> +		return ctrl.Result{Requeue: true}, nil
Same as the previous

2025-01-09 16:48 UTC, christinaexyou commented on config/overlays/odh/params.env
> +guardrails-orchestrator-image=quay.io/rh-ee-mmisiura/fms-orchestr8-nlp:0.7.0
renamed to `quay.io/trustyai/ta-guardrails-orchestrator:latest`

2025-01-09 16:49 UTC, christinaexyou commented on controllers/gorch/constants.go
> +	orchestratorImage = string("quay.io/rh-ee-mmisiura/fms-orchestr8-nlp:main_79434f")
added a new file `controllers/gorch/configmap.go` to fetch the orchestrator container image from a configmap object

2025-01-09 16:51 UTC, christinaexyou commented on controllers/gorch/templates/deployment.tmpl.yaml
> +                app: {{.Name}}
added new constants orchestratorName and version and added labels to the deployment template

2025-01-09 16:52 UTC, christinaexyou commented on controllers/utils/utils.go
>  import (
removed parsers and updated template paths

2025-01-09 17:35 UTC, evaline-ju commented on controllers/gorch/constants.go
> +	Version               = "0.7.0"
Since the `latest` image I assume can be easily upgraded at any time with any orchestrator version, is it typical to also track the orchestrator version here in the operator? (Wouldn't it be easy to get out of sync?)

2025-01-09 19:11 UTC, evaline-ju commented on controllers/gorch/templates/route.tmpl.yaml
> +kind: Route
For cases where the orchestrator server has been enabled with TLS, we've tended to create a separate route for the health endpoint that does not require TLS and can be used for probes. I assume that's not necessary for the use case here?

2025-01-09 19:13 UTC, evaline-ju commented on controllers/gorch/templates/deployment.tmpl.yaml
> +                      value: 'fms_guardrails_orchestr8=trace,tower_grpc=debug'
nit: would advise defaulting to `info`, or there could be a lot of logs (and potentially customer request info in prod settings)

2025-01-13 14:04 UTC, christinaexyou commented on controllers/gorch/constants.go
> +	Version               = "0.7.0"
This is for consistency since we track both the TrustyAI and LMES version. How many new stable releases of the orchestrator are there in a sprint and do we plan on syncing the operator with the most updated release every sprint ? cc: @RobGeada @ruivieira

2025-01-13 14:05 UTC, christinaexyou commented on controllers/gorch/templates/route.tmpl.yaml
> +kind: Route
Yes we definitely need to configure TLS at some point so that's good to know. But given that our current use case is KServe RawDeployment it's not necessary yet.

2025-01-13 21:21 UTC, ruivieira requested changes

2025-01-13 21:21 UTC, ruivieira commented on PROJECT
> +  group: gorch
Should this be kept under the `trustyai` group?

2025-01-13 21:26 UTC, ruivieira commented on controllers/gorch/constants.go
> +	Version               = "0.7.0"
@evaline-ju @christinaexyou We wouldn't add a default image to the controller, here. I think that for consistency:
- We get this value from the operator's configuration `ConfigMap`
- Typically we keep the `main` branch always at `latest` and just add a specific version on the release branches by editing the `params.env`

@christinaexyou (except for fix releases) our release cadence would be a minor release of all components every 3 weeks. For upstream releases we can release the orchestrator from GHA on this repo (as we do TAS and LMES), but the orchestrator container manifest would need some changes.

2025-01-14 15:04 UTC, christinaexyou commented on controllers/gorch/constants.go
> +	Version               = "0.7.0"
@ruivieira the default image is a fall back option if there's no configmap detected in the orchestrator namespace

2025-01-15 09:45 UTC, ruivieira commented on controllers/gorch/constants.go
> +	Version               = "0.7.0"
@christinaexyou For sure, and I understand the logic of it. My only question regarding this is (within the TrustyAI context), is that the orchestrator is always deployed and managed by the TrustyAI operator. 

So a missing TrustyAI operator's ConfigMap is a not a supported scenario, since if that ConfigMap is missing, the operator wouldn't be working correctly anyway. 

For instance there is the scenario where you can deploy a TrustyAI operator with a specific version requirement, delete the ConfigMap, and while it's not recreated a new orchestrator would deploy a `latest` orchestrator. In this case, it is better for the orchestrator to fail due to a missing operators ConfigMap, IMO.

2025-02-05 15:49 UTC, christinaexyou commented
closing because this branch has been since outdated. new PR here: https://github.com/trustyai-explainability/trustyai-service-operator/pull/403/checks

2025-02-05 15:49 UTC, closed without merging